AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Grails Forge API - grails-forge::grails-forge
Globals:
  Api:
    EndpointConfiguration: REGIONAL
Resources:
  GrailsForgeFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: not.used.in.provided.runtime
      Runtime: provided
      CodeUri: build/function.zip
      MemorySize: 128
      Policies: AWSLambdaBasicExecutionRole
      Timeout: 15
      Events:
        GetResource:
          Type: Api
          Properties:
            Path: /{proxy+}
            Method: any
Outputs:
  MicronautStarterApi:
    Description: URL for application
    Value: !Sub 'https://${GrailsForgeFunction}.execute-api.${AWS::Region}.amazonaws.com/'
    Export:
      Name: GrailsForgeApi
